#!/bin/bash


cd $OPENSHIFT_DATA_DIR

if [ ! -d apache-maven-3.3.9 ]; then
  wget http://apache.volia.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  tar -zxf apache-maven-3.3.9-bin.tar.gz
fi

cd $OPENSHIFT_REPO_DIR
mkdir -p $OPENSHIFT_DATA_DIR/m2/repository
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH


$OPENSHIFT_DATA_DIR/apache-maven-3.3.9/bin/mvn  -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/m2/repository  clean install
